import Head from 'next/head'
import React from 'react'

const about = () => {
    return (
        <>
            <Head>
                <title>Wisdom Ezekiel | Sign Up</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='h-[90vh] flex flex-col items-center max-w-7xl mx-auto p-4'>
                <h1 className='mt-10 text-2xl font-medium'>About Wisdom Ezekiel</h1>
            </div>
        </>
    )
}

export default about
