import Head from 'next/head'
import React from 'react'

const Company = () => {
    return (
        <>
            <Head>
                <title>Wisdom Ezekiel | Company</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className='bg-[#0d0e18] text-white'>
                <div className='min-h-screen max-w-7xl mx-auto'>
                    <h1 className='mr-auto md:mr-none text-center text-3xl font-bold pt-4 md:pt-8'>Company</h1>
                    <p className='mr-auto md:mr-none text-center pt-2 md:pt-4'>   
                    Some of the companies I have worked with
                    </p>
                    <div className='mt-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8'>
                        {companies.map((company, index) => (
                            <div key={index} className='p-4'>
                                <h1 className='text-xl font-bold pb-6'>{company.name}</h1>
                                <p className='text-sm'>{company.description}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>
        </>
    )
}

export default Company



const companies = [
    {
        name: 'Pertinence Properties',
        description: 'Pertinence Properties provides you excellent products and services in areas such as Land and House ownership, Rent, Construction, Property Management, and more With a team of 13,000+ realtors, 15,000+ client base, 63 estate projects, 8 office locations; with presence in the United Kingdom, Canada, and the United Arab Emirates'
    },
    {
        name: 'RealVest',
        description: 'Traditionally, real estate investment has been restricted to a limited class with a high entry barrier. However, with RealVest, everyone can now enjoy secured returns on real estate investment. RealVest provides a digitally accessible real estate investment solution, RealVest is taking the lead in providing investment plans for all caliber of people for shared prosperity.'
    },
    {
        name: 'DataFirst Technologies',
        description: 'DataFirst Technologies Ltd is on a mission to build a formidable engineering team capable enough to empower individuals and grow businesses by developing quality technological solutions. We are committed to continuous learning in order to consistently solve problems and provide excellent customer satisfaction with world class technological solutions.'
    },
    {
        name: 'HostNowNow',
        description: 'HostNowNow is one of Nigeria’s fastest growing web hosting, domain registry, and server management companies. Committed to making web hosting and domain registration affordable and accessible to businesses and individuals of all sizes.'
    },
    {
        name: 'Rushtower Limited',
        description: 'Rushtower limited is a media company with two actively working subsidiaries in Redi Studios and Redrush Tv.'
    },
    {
        name: 'Quanta Africa',
        description: 'Quanta is on a mission to transform Africa through innovation, people empowerment, and enterprise development — smartly addressing challenges impeding the economic growth of the continent.'
    },

]