import Head from 'next/head';
import Image from 'next/image';
import React from 'react'
import wisdom2 from '../public/images/DSC01039.jpg'

const Contact = () => {
    const [formData, setFormData] = React.useState({
        name: '',
        email: '',
        phone: '',
        message: ''
    });

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        const { name, value } = e.target;
        setFormData((prev) => ({
            ...prev,
            [name]: value
        }));
    };
    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        console.log(formData);
    };

    return (
        <>
            <Head>
                <title>Wisdom Ezekiel | Sign Up</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className='bg-[#0d0e18] text-white pt-4 h-[90vh] w-full flex flex-col md:flex-row justify-start items-center'>
                <div className='w-0 h-0 md:w-[50%] md:h-full hidden md:flex'>
                    <Image src={wisdom2} alt='Wisdom Ezekiel' className='object-cover object-center w-full h-full' />
                </div>
                <div className='flex flex-col justify center items-center w-full md:w-[50%] p-4'>
                    <h1 className='mt-10 text-2xl font-medium'>Sign up as a mentee</h1>
                    <p className='mb-10 text-sm pt-2 text-center'>Fill out the form below to sign up as a mentee under Wisdom Ezekiel</p>

                    {/* Form */}
                    <form className='flex flex-col space-y-4 w-full max-w-[500px] mx-auto' onSubmit={handleSubmit}>
                        <div className='flex flex-col gap-2 w-full'>
                            <label className='text-sm form-label' htmlFor='name'>Full Name</label>
                            <input type='text' name='name' id='name' className='form-input' placeholder='Enter your name' onChange={handleChange} value={formData.name} />
                        </div>
                        <div className='flex flex-col gap-2 w-full'>
                            <label className='text-sm form-label' htmlFor='email'>Email</label>
                            <input type='email' name='email' id='email' className='form-input' placeholder='Enter your email' onChange={handleChange} value={formData.email} />
                        </div>
                        <div className='flex flex-col gap-2 w-full'>
                            <label className='text-sm form-label' htmlFor='phone'>Phone</label>
                            <input type='tel' name='phone' id='phone' className='form-input' placeholder='Enter your phone number' onChange={handleChange} value={formData.phone} />
                        </div>
                        <div className='flex flex-col gap-2 w-full'>
                            <label className='text-sm form-label' htmlFor='message'>Message</label>
                            <textarea name='message' id='message' rows={3} className='form-input' placeholder='Enter your message' onChange={handleChange} value={formData.message} />
                        </div>
                        <div className='w-full mt-6'>
                            <button type='submit' className='btn-blue-submit mt-6 rounded'>Submit</button>
                        </div>
                    </form>
                </div>
            </section>
        </>
    )
}

export default Contact
